#!/usr/bin/env bash
# "Herdr Mobile: Setup" pane — relay status and the pairing link/QR for the phone.
#
# When it runs: herdr executes the pane's command (from [[panes]]) when the
# pane is opened — via the show-pair-link action (see open-pane.sh) or by hand
# with `herdr plugin pane open --plugin herdrelay.events --entrypoint setup`.
# The pane prints state into a zoomed pane of the herdr terminal and closes
# itself via the sleep at the bottom (herdr closes the pane when the process
# exits).
#
# The QR is generated by the relay itself: `herdrelay pair --qr` prints a
# herdrelay://pair?... link as ANSI half-blocks straight into the terminal —
# the phone scans it.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
BIN="$ROOT/bin/herdrelay"
PORT="${HERDRELAY_PORT:-8375}"

echo "== Herdr Mobile: status =="
if curl -s -m 2 "http://127.0.0.1:${PORT}/healthz" >/dev/null; then
    echo "relay: running on :${PORT}"
    echo
    echo "== Phone link / QR (scan in the Herdr Mobile app) =="
    if [ -x "$BIN" ]; then
        "$BIN" pair --qr
    else
        echo "relay binary missing: run 'bash $ROOT/install.sh'" >&2
    fi
else
    echo "relay: NOT running"
    echo "Start it: launchctl start com.herdrelay.relay   (or 'bash $ROOT/install.sh')"
fi

echo
echo "This pane closes by itself."
sleep 15
